### ISSUE TITLE
AppImage fails to launch

### ISSUE THREAD

**Issue by Quinten0508** [Tenpi/Waifu2x-GUI#11]
System info: EndeavourOS x86_64 kernel 6.3.1-arch1-1 (Arch derivative)

When running the AppImage the following is outputted to the terminal (./Waifu2x-GUI-0.4.0.AppImage):
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error:
Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
at Object.<anonymous> (/tmp/.mount_Waifu2Bs9nva/resources/app.asar/node_modules/sharp/lib/sharp.js:34:9)
at Module._compile (internal/modules/cjs/loader.js:1083:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1113:10)
at Module.load (internal/modules/cjs/loader.js:940:32)
at Module._load (internal/modules/cjs/loader.js:781:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
at Module.require (internal/modules/cjs/loader.js:964:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/tmp/.mount_Waifu2Bs9nva/resources/app.asar/node_modules/sharp/lib/constructor.js:8:1)
at Module._compile (internal/modules/cjs/loader.js:1083:30)

(waifu2x-gui:371768): Gtk-WARNING **: 18:55:21.430: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(waifu2x-gui:371768): Gtk-WARNING **: 18:55:21.430: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

The process does not stop, but no UI opens and no further info is outputted on the terminal.

I can install the `sharp` npm module, like the output recommends just fine (no errors), but this does not have any effect on the appimage functioning.  Here's the output of that npm install, although I doubt it'll be of any use:
```
$ npm install --ignore-scripts=false --foreground-scripts --verbose sharp
npm verb cli /home/quinten/.nvm/versions/node/v18.15.0/bin/node /home/quinten/.nvm/versions/node/v18.15.0/bin/npm
npm info using npm@9.6.3
npm info using node@v18.15.0
npm verb title npm install sharp
npm verb argv "install" "--ignore-scripts" "false" "--foreground-scripts" "--loglevel" "verbose" "sharp"
npm verb logfile logs-max:10 dir:/home/quinten/.npm/_logs/2023-05-07T16_58_35_610Z-
npm verb logfile /home/quinten/.npm/_logs/2023-05-07T16_58_35_610Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp 136ms (cache revalidated)
npm info run sharp@0.32.1 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

> sharp@0.32.1 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 208ms
sharp: Using cached /home/quinten/.npm/_libvips/libvips-8.14.2-linux-x64.tar.brorg/-/npm/v1/security/advisories/bulk 208ms
sharp: Integrity check passed for linux-x64tch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 208ms
prebuild-install info begin Prebuild-install version 7.1.1tps://registry.npmjs.org/-/npm/v1/security/advisories/bulk 208ms
prebuild-install info looking for local prebuild @ prebuilds/sharp-v0.32.1-napi-v7-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/quinten/.npm/_prebuilds/8ad733-sharp-v0.32.1-napi-v7-linux-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /home/quinten/.npm/_prebuilds/8ad733-sharp-v0.32.1-napi-v7-linux-x64.tar.gz
prebuild-install info unpack resolved to /home/quinten/Downloads/node_modules/sharp/build/Release/sharp-linux-x64.node08ms
prebuild-install info install Successfully installed prebuilt binary!
npm info run sharp@0.32.1 install { code: 0, signal: null }

added 45 packages, and audited 46 packages in 1s

10 packages are looking for funding
run `npm fund` for details

found 0 vulnerabilities
npm verb exit 0
npm info ok
```

**Comment by Quinten0508** [comment]
Just wanted to add that I've also tried compiling from source using the instructions you provided [here](https://github.com/DeadSix27/waifu2x-converter-cpp/blob/master/BUILDING.md#linux), but this also fails with a rather lengthy output, which I'll paste below. This is another issue all together, but since the build instructions you linked to were from another author/repo, which has been archived, I didn't open a new issue here.

System info: 
* EndeavourOS x86_64 kernel 6.3.1-arch1-1 (Arch derivative) 
* gcc (GCC) 13.1.1 20230429
* all other requirements (including the Arch-specific ones) are installed

```
$ make -j4
[  4%] Building C object CMakeFiles/conv.dir/conv.c.o
[  8%] Linking C executable conv
[  8%] Built target conv
[ 13%] Generating modelHandler_OpenCL.cl.h
[ 17%] Generating modelHandler_CUDA.ptx52
/usr/include/stdlib.h(141): error: identifier "_Float32" is undefined
extern _Float32 strtof32 (const char *__restrict __nptr,
^

/usr/include/stdlib.h(147): error: identifier "_Float64" is undefined
extern _Float64 strtof64 (const char *__restrict __nptr,
^

/usr/include/stdlib.h(153): error: identifier "_Float128" is undefined
extern _Float128 strtof128 (const char *__restrict __nptr,
^

/usr/include/stdlib.h(159): error: identifier "_Float32x" is undefined
extern _Float32x strtof32x (const char *__restrict __nptr,
^

/usr/include/stdlib.h(165): error: identifier "_Float64x" is undefined
extern _Float64x strtof64x (const char *__restrict __nptr,
^

/usr/include/stdlib.h(234): error: identifier "_Float32" is undefined
_Float32 __f)
^

/usr/include/stdlib.h(240): error: identifier "_Float64" is undefined
_Float64 __f)
^

/usr/include/stdlib.h(246): error: identifier "_Float128" is undefined
_Float128 __f)
^

/usr/include/stdlib.h(252): error: identifier "_Float32x" is undefined
_Float32x __f)
^

/usr/include/stdlib.h(258): error: identifier "_Float64x" is undefined
_Float64x __f)
^

/usr/include/stdlib.h(317): error: identifier "_Float32" is undefined
extern _Float32 strtof32_l (const char *__restrict __nptr,
^

/usr/include/stdlib.h(324): error: identifier "_Float64" is undefined
extern _Float64 strtof64_l (const char *__restrict __nptr,
^

/usr/include/stdlib.h(331): error: identifier "_Float128" is undefined
extern _Float128 strtof128_l (const char *__restrict __nptr,
^

/usr/include/stdlib.h(338): error: identifier "_Float32x" is undefined
extern _Float32x strtof32x_l (const char *__restrict __nptr,
^

/usr/include/stdlib.h(345): error: identifier "_Float64x" is undefined
extern _Float64x strtof64x_l (const char *__restrict __nptr,
^

/usr/include/bits/mathcalls.h(53): error: identifier "_Float32" is undefined
extern _Float32 acosf32 (_Float32 __x) noexcept (true); extern _Float32 __acosf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(53): error: identifier "_Float32" is undefined
extern _Float32 acosf32 (_Float32 __x) noexcept (true); extern _Float32 __acosf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(53): error: identifier "_Float32" is undefined
extern _Float32 acosf32 (_Float32 __x) noexcept (true); extern _Float32 __acosf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(53): error: identifier "_Float32" is undefined
extern _Float32 acosf32 (_Float32 __x) noexcept (true); extern _Float32 __acosf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(55): error: identifier "_Float32" is undefined
extern _Float32 asinf32 (_Float32 __x) noexcept (true); extern _Float32 __asinf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(55): error: identifier "_Float32" is undefined
extern _Float32 asinf32 (_Float32 __x) noexcept (true); extern _Float32 __asinf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(55): error: identifier "_Float32" is undefined
extern _Float32 asinf32 (_Float32 __x) noexcept (true); extern _Float32 __asinf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(55): error: identifier "_Float32" is undefined
extern _Float32 asinf32 (_Float32 __x) noexcept (true); extern _Float32 __asinf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(57): error: identifier "_Float32" is undefined
extern _Float32 atanf32 (_Float32 __x) noexcept (true); extern _Float32 __atanf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(57): error: identifier "_Float32" is undefined
extern _Float32 atanf32 (_Float32 __x) noexcept (true); extern _Float32 __atanf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(57): error: identifier "_Float32" is undefined
extern _Float32 atanf32 (_Float32 __x) noexcept (true); extern _Float32 __atanf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(57): error: identifier "_Float32" is undefined
extern _Float32 atanf32 (_Float32 __x) noexcept (true); extern _Float32 __atanf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(59): error: identifier "_Float32" is undefined
extern _Float32 atan2f32 (_Float32 __y, _Float32 __x) noexcept (true); extern _Float32 __atan2f32 (_Float32 __y, _Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(59): error: identifier "_Float32" is undefined
extern _Float32 atan2f32 (_Float32 __y, _Float32 __x) noexcept (true); extern _Float32 __atan2f32 (_Float32 __y, _Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(59): error: identifier "_Float32" is undefined
extern _Float32 atan2f32 (_Float32 __y, _Float32 __x) noexcept (true); extern _Float32 __atan2f32 (_Float32 __y, _Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(59): error: identifier "_Float32" is undefined
extern _Float32 atan2f32 (_Float32 __y, _Float32 __x) noexcept (true); extern _Float32 __atan2f32 (_Float32 __y, _Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(59): error: identifier "_Float32" is undefined
extern _Float32 atan2f32 (_Float32 __y, _Float32 __x) noexcept (true); extern _Float32 __atan2f32 (_Float32 __y, _Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(59): error: identifier "_Float32" is undefined
extern _Float32 atan2f32 (_Float32 __y, _Float32 __x) noexcept (true); extern _Float32 __atan2f32 (_Float32 __y, _Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(62): error: identifier "_Float32" is undefined
extern _Float32 cosf32 (_Float32 __x) noexcept (true); extern _Float32 __cosf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(62): error: identifier "_Float32" is undefined
extern _Float32 cosf32 (_Float32 __x) noexcept (true); extern _Float32 __cosf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(62): error: identifier "_Float32" is undefined
extern _Float32 cosf32 (_Float32 __x) noexcept (true); extern _Float32 __cosf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(62): error: identifier "_Float32" is undefined
extern _Float32 cosf32 (_Float32 __x) noexcept (true); extern _Float32 __cosf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(64): error: identifier "_Float32" is undefined
extern _Float32 sinf32 (_Float32 __x) noexcept (true); extern _Float32 __sinf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(64): error: identifier "_Float32" is undefined
extern _Float32 sinf32 (_Float32 __x) noexcept (true); extern _Float32 __sinf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(64): error: identifier "_Float32" is undefined
extern _Float32 sinf32 (_Float32 __x) noexcept (true); extern _Float32 __sinf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(64): error: identifier "_Float32" is undefined
extern _Float32 sinf32 (_Float32 __x) noexcept (true); extern _Float32 __sinf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(66): error: identifier "_Float32" is undefined
extern _Float32 tanf32 (_Float32 __x) noexcept (true); extern _Float32 __tanf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(66): error: identifier "_Float32" is undefined
extern _Float32 tanf32 (_Float32 __x) noexcept (true); extern _Float32 __tanf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(66): error: identifier "_Float32" is undefined
extern _Float32 tanf32 (_Float32 __x) noexcept (true); extern _Float32 __tanf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(66): error: identifier "_Float32" is undefined
extern _Float32 tanf32 (_Float32 __x) noexcept (true); extern _Float32 __tanf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(71): error: identifier "_Float32" is undefined
extern _Float32 coshf32 (_Float32 __x) noexcept (true); extern _Float32 __coshf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(71): error: identifier "_Float32" is undefined
extern _Float32 coshf32 (_Float32 __x) noexcept (true); extern _Float32 __coshf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(71): error: identifier "_Float32" is undefined
extern _Float32 coshf32 (_Float32 __x) noexcept (true); extern _Float32 __coshf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(71): error: identifier "_Float32" is undefined
extern _Float32 coshf32 (_Float32 __x) noexcept (true); extern _Float32 __coshf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(73): error: identifier "_Float32" is undefined
extern _Float32 sinhf32 (_Float32 __x) noexcept (true); extern _Float32 __sinhf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(73): error: identifier "_Float32" is undefined
extern _Float32 sinhf32 (_Float32 __x) noexcept (true); extern _Float32 __sinhf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(73): error: identifier "_Float32" is undefined
extern _Float32 sinhf32 (_Float32 __x) noexcept (true); extern _Float32 __sinhf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(73): error: identifier "_Float32" is undefined
extern _Float32 sinhf32 (_Float32 __x) noexcept (true); extern _Float32 __sinhf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(75): error: identifier "_Float32" is undefined
extern _Float32 tanhf32 (_Float32 __x) noexcept (true); extern _Float32 __tanhf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(75): error: identifier "_Float32" is undefined
extern _Float32 tanhf32 (_Float32 __x) noexcept (true); extern _Float32 __tanhf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(75): error: identifier "_Float32" is undefined
extern _Float32 tanhf32 (_Float32 __x) noexcept (true); extern _Float32 __tanhf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(75): error: identifier "_Float32" is undefined
extern _Float32 tanhf32 (_Float32 __x) noexcept (true); extern _Float32 __tanhf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(79): error: identifier "_Float32" is undefined
extern void sincosf32 (_Float32 __x, _Float32 *__sinx, _Float32 *__cosx) noexcept (true); extern void __sincosf32 (_Float32 __x, _Float32 *__sinx, _Float32 *__cosx) noexcept (true)
^

/usr/include/bits/mathcalls.h(79): error: identifier "_Float32" is undefined
extern void sincosf32 (_Float32 __x, _Float32 *__sinx, _Float32 *__cosx) noexcept (true); extern void __sincosf32 (_Float32 __x, _Float32 *__sinx, _Float32 *__cosx) noexcept (true)
^

/usr/include/bits/mathcalls.h(79): error: identifier "_Float32" is undefined
extern void sincosf32 (_Float32 __x, _Float32 *__sinx, _Float32 *__cosx) noexcept (true); extern void __sincosf32 (_Float32 __x, _Float32 *__sinx, _Float32 *__cosx) noexcept (true)
^

/usr/include/bits/mathcalls.h(79): error: identifier "_Float32" is undefined
extern void sincosf32 (_Float32 __x, _Float32 *__sinx, _Float32 *__cosx) noexcept (true); extern void __sincosf32 (_Float32 __x, _Float32 *__sinx, _Float32 *__cosx) noexcept (true)
^

/usr/include/bits/mathcalls.h(79): error: identifier "_Float32" is undefined
extern void sincosf32 (_Float32 __x, _Float32 *__sinx, _Float32 *__cosx) noexcept (true); extern void __sincosf32 (_Float32 __x, _Float32 *__sinx, _Float32 *__cosx) noexcept (true)
^

/usr/include/bits/mathcalls.h(79): error: identifier "_Float32" is undefined
extern void sincosf32 (_Float32 __x, _Float32 *__sinx, _Float32 *__cosx) noexcept (true); extern void __sincosf32 (_Float32 __x, _Float32 *__sinx, _Float32 *__cosx) noexcept (true)
^

/usr/include/bits/mathcalls.h(85): error: identifier "_Float32" is undefined
extern _Float32 acoshf32 (_Float32 __x) noexcept (true); extern _Float32 __acoshf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(85): error: identifier "_Float32" is undefined
extern _Float32 acoshf32 (_Float32 __x) noexcept (true); extern _Float32 __acoshf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(85): error: identifier "_Float32" is undefined
extern _Float32 acoshf32 (_Float32 __x) noexcept (true); extern _Float32 __acoshf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(85): error: identifier "_Float32" is undefined
extern _Float32 acoshf32 (_Float32 __x) noexcept (true); extern _Float32 __acoshf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(87): error: identifier "_Float32" is undefined
extern _Float32 asinhf32 (_Float32 __x) noexcept (true); extern _Float32 __asinhf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(87): error: identifier "_Float32" is undefined
extern _Float32 asinhf32 (_Float32 __x) noexcept (true); extern _Float32 __asinhf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(87): error: identifier "_Float32" is undefined
extern _Float32 asinhf32 (_Float32 __x) noexcept (true); extern _Float32 __asinhf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(87): error: identifier "_Float32" is undefined
extern _Float32 asinhf32 (_Float32 __x) noexcept (true); extern _Float32 __asinhf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(89): error: identifier "_Float32" is undefined
extern _Float32 atanhf32 (_Float32 __x) noexcept (true); extern _Float32 __atanhf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(89): error: identifier "_Float32" is undefined
extern _Float32 atanhf32 (_Float32 __x) noexcept (true); extern _Float32 __atanhf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(89): error: identifier "_Float32" is undefined
extern _Float32 atanhf32 (_Float32 __x) noexcept (true); extern _Float32 __atanhf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(89): error: identifier "_Float32" is undefined
extern _Float32 atanhf32 (_Float32 __x) noexcept (true); extern _Float32 __atanhf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(95): error: identifier "_Float32" is undefined
extern _Float32 expf32 (_Float32 __x) noexcept (true); extern _Float32 __expf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(95): error: identifier "_Float32" is undefined
extern _Float32 expf32 (_Float32 __x) noexcept (true); extern _Float32 __expf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(95): error: identifier "_Float32" is undefined
extern _Float32 expf32 (_Float32 __x) noexcept (true); extern _Float32 __expf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(95): error: identifier "_Float32" is undefined
extern _Float32 expf32 (_Float32 __x) noexcept (true); extern _Float32 __expf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(98): error: identifier "_Float32" is undefined
extern _Float32 frexpf32 (_Float32 __x, int *__exponent) noexcept (true); extern _Float32 __frexpf32 (_Float32 __x, int *__exponent) noexcept (true);
^

/usr/include/bits/mathcalls.h(98): error: identifier "_Float32" is undefined
extern _Float32 frexpf32 (_Float32 __x, int *__exponent) noexcept (true); extern _Float32 __frexpf32 (_Float32 __x, int *__exponent) noexcept (true);
^

/usr/include/bits/mathcalls.h(98): error: identifier "_Float32" is undefined
extern _Float32 frexpf32 (_Float32 __x, int *__exponent) noexcept (true); extern _Float32 __frexpf32 (_Float32 __x, int *__exponent) noexcept (true);
^

/usr/include/bits/mathcalls.h(98): error: identifier "_Float32" is undefined
extern _Float32 frexpf32 (_Float32 __x, int *__exponent) noexcept (true); extern _Float32 __frexpf32 (_Float32 __x, int *__exponent) noexcept (true);
^

/usr/include/bits/mathcalls.h(101): error: identifier "_Float32" is undefined
extern _Float32 ldexpf32 (_Float32 __x, int __exponent) noexcept (true); extern _Float32 __ldexpf32 (_Float32 __x, int __exponent) noexcept (true);
^

/usr/include/bits/mathcalls.h(101): error: identifier "_Float32" is undefined
extern _Float32 ldexpf32 (_Float32 __x, int __exponent) noexcept (true); extern _Float32 __ldexpf32 (_Float32 __x, int __exponent) noexcept (true);
^

/usr/include/bits/mathcalls.h(101): error: identifier "_Float32" is undefined
extern _Float32 ldexpf32 (_Float32 __x, int __exponent) noexcept (true); extern _Float32 __ldexpf32 (_Float32 __x, int __exponent) noexcept (true);
^

/usr/include/bits/mathcalls.h(101): error: identifier "_Float32" is undefined
extern _Float32 ldexpf32 (_Float32 __x, int __exponent) noexcept (true); extern _Float32 __ldexpf32 (_Float32 __x, int __exponent) noexcept (true);
^

/usr/include/bits/mathcalls.h(104): error: identifier "_Float32" is undefined
extern _Float32 logf32 (_Float32 __x) noexcept (true); extern _Float32 __logf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(104): error: identifier "_Float32" is undefined
extern _Float32 logf32 (_Float32 __x) noexcept (true); extern _Float32 __logf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(104): error: identifier "_Float32" is undefined
extern _Float32 logf32 (_Float32 __x) noexcept (true); extern _Float32 __logf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(104): error: identifier "_Float32" is undefined
extern _Float32 logf32 (_Float32 __x) noexcept (true); extern _Float32 __logf32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(107): error: identifier "_Float32" is undefined
extern _Float32 log10f32 (_Float32 __x) noexcept (true); extern _Float32 __log10f32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(107): error: identifier "_Float32" is undefined
extern _Float32 log10f32 (_Float32 __x) noexcept (true); extern _Float32 __log10f32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(107): error: identifier "_Float32" is undefined
extern _Float32 log10f32 (_Float32 __x) noexcept (true); extern _Float32 __log10f32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(107): error: identifier "_Float32" is undefined
extern _Float32 log10f32 (_Float32 __x) noexcept (true); extern _Float32 __log10f32 (_Float32 __x) noexcept (true);
^

/usr/include/bits/mathcalls.h(110): error: identifier "_Float32" is undefined
extern _Float32 modff32 (_Float32 __x, _Float32 *__iptr) noexcept (true); extern _Float32 __modff32 (_Float32 __x, _Float32 *__iptr) noexcept (true)__attribute__ ((__nonnull__ (2)));
^

/usr/include/bits/mathcalls.h(110): error: identifier "_Float32" is undefined
extern _Float32 modff32 (_Float32 __x, _Float32 *__iptr) noexcept (true); extern _Float32 __modff32 (_Float32 __x, _Float32 *__iptr) noexcept (true)__attribute__ ((__nonnull__ (2)));
^

/usr/include/bits/mathcalls.h(110): error: identifier "_Float32" is undefined
extern _Float32 modff32 (_Float32 __x, _Float32 *__iptr) noexcept (true); extern _Float32 __modff32 (_Float32 __x, _Float32 *__iptr) noexcept (true)__attribute__ ((__nonnull__ (2)));
^

/usr/include/bits/mathcalls.h(110): error: identifier "_Float32" is undefined
extern _Float32 modff32 (_Float32 __x, _Float32 *__iptr) noexcept (true); extern _Float32 __modff32 (_Float32 __x, _Float32 *__iptr) noexcept (true)__attribute__ ((__nonnull__ (2)));
^

/usr/include/bits/mathcalls.h(110): error: identifier "_Float32" is undefined
extern _Float32 modff32 (_Float32 __x, _Float32 *__iptr) noexcept (true); extern _Float32 __modff32 (_Float32 __x, _Float32 *__iptr) noexcept (true)__attribute__ ((__nonnull__ (2)));
^

Error limit reached.
100 errors detected in the compilation of "/home/quinten/gitfiles/waifu2x-converter-cpp/src/modelHandler_CUDA.cu".
Compilation terminated.
make[2]: *** [CMakeFiles/gensrcs.dir/build.make:84: modelHandler_CUDA.ptx52] Error 1
make[1]: *** [CMakeFiles/Makefile2:141: CMakeFiles/gensrcs.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by Tenpi** [comment]
I'm not sure why you tried building that other project, you are supposed to build this one.
```
git clone https://github.com/Tenpi/Waifu2x-GUI.git
npm install
npm run sharp:linux
npm run build
```
If sharp doesn't work you can remove it from the source code, it is only used for compression.

**Comment by senjacob** [comment]
> I'm not sure why you tried building that other project, you are supposed to build this one. (it isn't mine btw)
> 
> ```
> git clone https://github.com/Tenpi/Waifu2x-GUI.git
> npm install
> npm run sharp:linux
> npm run build
> ```
> 
> If sharp doesn't work you can remove it from the source code, it is only used for compression.

Got below error on `npm run build` in KUbuntu 23.04, x11, NVidia Driver Version: 535.86.05    CUDA Version: 12.2

> waifu2x-gui@0.4.1 build
> npm run clean ./build && webpack && electron-builder -p never


> waifu2x-gui@0.4.1 clean
> del-cli ./dist ./build


/mnt/Apps/Waifu2x-GUI/node_modules/loader-runner/lib/LoaderRunner.js:146
                if(isError) throw e;
                            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/mnt/Apps/Waifu2x-GUI/node_modules/webpack/lib/util/createHash.js:144:18)
    at BulkUpdateDecorator.update (/mnt/Apps/Waifu2x-GUI/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/mnt/Apps/Waifu2x-GUI/node_modules/webpack-sources/lib/RawSource.js:64:8)
    at NormalModule._initBuildHash (/mnt/Apps/Waifu2x-GUI/node_modules/webpack/lib/NormalModule.js:752:17)
    at handleParseResult (/mnt/Apps/Waifu2x-GUI/node_modules/webpack/lib/NormalModule.js:816:10)
    at /mnt/Apps/Waifu2x-GUI/node_modules/webpack/lib/NormalModule.js:907:4
    at processResult (/mnt/Apps/Waifu2x-GUI/node_modules/webpack/lib/NormalModule.js:639:11)
    at /mnt/Apps/Waifu2x-GUI/node_modules/webpack/lib/NormalModule.js:691:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.17.1
